---
- hosts: all
  sudo: true
  vars:
    doc_root: /vagrant/web
    server_name: "{{ ansible_eth1.ipv4.address }}"
    sys_packages: [ 'curl', 'vim', 'git']
    php_packages: [ 'php5-curl', 'php5-cli' ]
  roles:
    - init
    - nginxphp
